apiVersion: v2
name: gliding-club-crm
version: 0.0.1
description: A Helm chart for Gliding Action Manager

dependencies:
  - name: gliding-club-crm-client
    version: 0.0.1
    repository: file://../../client/helm
  - name: gliding-club-crm-server
    version: 0.0.1
    repository: file://../../server/helm
  - name: postgresql
    version: 12.1.3
    repository: https://charts.bitnami.com/bitnami
