version: "3.9"

services:
  frontend:
    image: "node:14-alpine"
    working_dir: /app
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=production
    ports:
      - "4200:4200"
    command: "yarn start"
    depends_on:
      backend:
        condition: service_healthy
  backend:
    image: "node:14-alpine"
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mgc_admin
    ports:
      - "4000:4000"
    command: "yarn start"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "http.request({host: 'localhost', port: '4000'}).end()"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  db:
    image: postgres:14-alpine
    user: postgres
    environment:
      - POSTGRES_DB=mgc_admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
