version: "3.9"

services:
  frontend:
    build: client
    image: localhost:5001/gliding-club-crm-client
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "http.request({host: 'localhost', port: '8080'}).end()"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3002:3000"
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build: server
    image: localhost:5001/gliding-club-crm-server
    volumes:
      - ./data/logs:/app/server/logs
    environment:
      - NODE_ENV=development
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - CREATE_SEED_DATA=true
    ports:
      - "4001:4000"
    command: "yarn start"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "http.request({host: 'localhost', port: '4000'}).end()"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
  db:
    image: postgres:14-alpine
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
