services:
  frontend:
    image: "node:14-alpine"
    working_dir: /app
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=production
    ports:
      - "4200:4200"
    command: "yarn start"
    depends_on:
      backend:
        condition: service_healthy
  backend:
    extends:
      file: docker-compose.yml
      service: backend
  db:
    extends:
      file: docker-compose.yml
      service: db

volumes:
  db_data: